/* Groove Bank rhythm library, transcribed verbatim from mission-minnow/groovebank (src/patterns/, one .groove file per genre).
 * Copyright (c) 2026 mission-minnow, MIT License (see LICENSE-groovebank). Generated -- do not edit.
 * One entry per groove: genre index, name, step count, up to 3 lanes (hit:, alt:, alt:) with
 * x = hit, A = accent, g = ghost, - = tie (held), . = rest. drumgen_vst.cpp turns the lanes into
 * DRUMGEN-style probability layers (see gb_layers()). */
#pragma once
static const char *const GB_GENRES[] = {"HOUSE", "TECHNO", "GARAGE", "DNB", "HIPHOP", "TRAP", "FUNK", "SOUL", "JAZZ", "LATIN", "REGGAE", "ROCK", "AFRO", "WORLD"};
#define GB_NGENRES 14
struct gb_groove { int genre; const char *name; int steps; const char *lanes[3]; };
static const gb_groove GROOVES[] = {
    {0, "Four Floor", 16, {"x...x...x...x...", "A...x...A...x...", "x...x...x...x..x"}},
    {0, "Offbeat Stab", 16, {"..x...x...x...x.", "..x.x.x...x.x.x.", "..A...x...A...x."}},
    {0, "Deep Chord", 16, {"..x-..x-..x-..x-", "..x-......x-....", "..A-..x-..A-..x-"}},
    {0, "Jackin", 16, {"x..x..x.x..x..x.", "x..x..A.x..x..A.", "x.gx..x.x.gx..x."}},
    {0, "Disco", 16, {"..x.x..x..x.x..x", "..x.x.x.x.x.x.x.", "..A.x..A..x.x..x"}},
    {0, "Piano Stab", 16, {"x...x..xx...x..x", "x...x...x...x...", "A...x..xA...x..x"}},
    {0, "Soulful", 16, {"x..x.x..x..x.x..", "x...x...x...x...", "x..x.gx.x..x.gx."}},
    {1, "Driving", 16, {"..x...x...x...xx", "..x...x...x...x.", "..A...A...A...A."}},
    {1, "Minimal", 16, {"..x.......x.....", "..x.............", "..x.....x......."}},
    {1, "Dub Techno", 16, {"..A-..x-..A-..x-", "..x-..x-..x-..x-", "..A-......A-...."}},
    {1, "Acid", 16, {"x.x..x.x.x..x.x.", "x.x.x.x.x.x.x.x.", "A.x..x.A.x..x.x."}},
    {1, "Detroit", 16, {"x..x.x..x..x.x..", "x...x...x...x...", "x..x.x..x.xx.x.."}},
    {1, "Hypnotic", 16, {"x..gx..gx..gx..g", "x...x...x...x...", "A..gx..gA..gx..g"}},
    {2, "2-Step", 16, {"x.....x..x....x.", "x.....x..x.x..x.", "x.....x..x......"}},
    {2, "UK Garage", 16, {"x..x.x..x..x.x..", "x..x.x..x.x.x.x.", "A..x.x..A..x.x.."}},
    {2, "Speed Garage", 16, {"x..x..x.x..x..x.", "x..x..x.x..x.xx.", "A..x..x.A..x..x."}},
    {2, "Bassline", 16, {"x..x.xx.x..x.xx.", "x..x..x.x..x..x.", "x..x.xx.x.xx.xx."}},
    {2, "4x4 Garage", 16, {"x...xx..x...xx..", "x...x...x...x...", "A...xx..A...xx.."}},
    {2, "Future", 16, {"..x....x..x.....", "..x.......x....x", "..x-...x..x-...."}},
    {3, "Two-Step", 16, {"x.....x...x...x.", "x.....x...x.....", "x.....x...x...xx"}},
    {3, "Liquid", 16, {"x..x..x...x..x..", "x.....x...x.....", "x..x..x.g.x..x.."}},
    {3, "Rollers", 16, {"x.xx.xx.x.xx.xx.", "x.x.x.x.x.x.x.x.", "A.xx.xx.A.xx.xx."}},
    {3, "Neurofunk", 16, {"x...x..x.x..x.x.", "x...x...x...x...", "A...x..x.A..x.x."}},
    {3, "Jump Up", 16, {"x..x..x..x..x..x", "x..x..x.x..x..x.", "A..x..A..A..x..x"}},
    {3, "Amen", 16, {"x..gx.xgx..gx.xg", "x...x...x...x...", "x..gx.xg.x..gx.x"}},
    {3, "Jungle", 16, {"x..x.x..gx.x..x.", "x..x.x..x..x..x.", "x...gx.xg.x.gx.."}},
    {4, "Boom Bap", 16, {"x.......x..x....", "x...g...x..x.g..", "A.......x..A...."}},
    {4, "G-Funk", 16, {"x...x....x.x....", "x..gx...gx.xg...", "A...x......x...."}},
    {4, "East Coast", 16, {"x....x.x...x..x.", "x..g.x.xg..x.gx.", "A....x.....x...."}},
    {4, "Dilla", 16, {"x.....x..gx....A", "x..g..xg.gx.g..A", "A........x......"}},
    {4, "Lofi", 16, {"x.....x....x....", "x..g..xg...x..g.", "A.....x....x...."}},
    {4, "Chillhop", 16, {"x....x..x...x...", "x.g..x.gx.g.x.g.", "A....x......x..."}},
    {4, "Trip Hop", 16, {"x.......x...x...", "x....g..x.g.x...", "A.......x......."}},
    {5, "Trap Stab", 16, {"x..........x....", "x......x...x....", "A..........A...."}},
    {5, "Half-Time", 16, {"x.......A.......", "x....x..A....x..", "A.......x......."}},
    {5, "Drill", 16, {"x.....x....x...x", "x..g..x.g..x.g.x", "A.....x....A...."}},
    {5, "Dark Stab", 16, {"x.........x.....", "x.....x...x...x.", "A.........A....."}},
    {5, "Bounce", 16, {"x..x....x...x..x", "x..xg..gx..gx..x", "A..x....A...x..."}},
    {5, "Trap Roll", 16, {"x..............x", "x.......x......x", "A.......gg.....A"}},
    {6, "Charleston", 16, {"x......x........", "x......x....x...", "A......gx......."}},
    {6, "16th Comp", 16, {"x.xxg.xxx.xxg.xx", "A.gxg.xxA.gxg.gx", "x..x..x...x..x.."}},
    {6, "Scratch", 16, {"g.Axg.xgg.Axg.xg", "gxAxgxxggxAxgxxg", "g..A..g.g..A..g."}},
    {6, "Clav", 16, {"x.g.A.gxx.g.A.gx", "xgg.AggxxggAAggx", "x...A...x...A..."}},
    {6, "Second Line", 16, {"x..x.gx.gx..x.g.", "A..x.gxggxg.x.gg", "x..x..x..x..x..."}},
    {6, "JB Push", 16, {"A..g..A.g..A..g.", "A.ggg.Aggg.AgggA", "A.....A....A...."}},
    {6, "Ghost Chop", 16, {"xg.gxg.gxg.gxg.g", "Ag.gxggAAg.gxggA", "x...x...x...x..."}},
    {6, "Disco Funk", 16, {"x...A...x...A..x", "x..gA..gx..gA.gx", "A...x...A...x..."}},
    {7, "Motown", 16, {"..x...x...x...x.", "..x.g.x.g.x.g.x.", "..A...x...A...x."}},
    {7, "Stax", 16, {"x...x..gx...x..g", "x..gx.ggx..gx.gg", "A...x...A...x..."}},
    {7, "Philly", 16, {"x..x..x.x..x..x.", "x.gx.gx.x.gx.gx.", "A..x..x.A..x..x."}},
    {7, "Neo Soul", 16, {"x..gx..A..gx..A.", "xg.gxg.Agggxg.A.", "A...x.....x...A."}},
    {7, "Quiet Storm", 16, {"x.....x...x.....", "x...g.x.g.x...g.", "A.........A....."}},
    {7, "Shout", 16, {"x.xx.xx.x.xx.xx.", "A.xxgxxgA.xxgxxg", "x..x..x.x..x..x."}},
    {7, "New Jack", 16, {"x.x..x.xx.x..x.x", "A.xg.x.xAgx.gx.x", "x...x...x...x..."}},
    {8, "Charleston", 16, {"x......x........", "x......x......x.", "..x....x........"}},
    {8, "Comp 2 And 4", 16, {"......x.....x...", "..x.........x..x", "......x...x..x.."}},
    {8, "Freddie Green", 16, {"x...x...x...x...", "x...g...x...g...", "A...x...A...x..."}},
    {8, "Bossa Comp", 16, {"x..x..x...x..x..", "x..x..x..x..x..x", "x..x....x..x...."}},
    {8, "Afro-Cuban", 16, {"x..x..x.x..x..x.", "x..x..x.x..x.x..", "x..x....x..x..x."}},
    {8, "Jazz Waltz", 12, {"x...x..x....", "x...x..x..x.", "x......x...."}},
    {8, "Ballad", 16, {"x.......x-......", "x.......x-....x.", "x..............."}},
    {9, "Tresillo", 16, {"x..x..x.x..x..x.", "x.xx..x.x.xx..x.", "x.....x.....x..."}},
    {9, "Son Clave", 16, {"x..x..x...x.x...", "..x.x...x..x..x.", "A..x..x...A.x..."}},
    {9, "Rumba Clave", 16, {"x..x...x..x.x...", "..x.x...x..x...x", "A..x...x..A.x..."}},
    {9, "Cascara", 16, {"x.x.xx.x.x.xx.x.", "A.x.xA.x.x.xA.x.", "x...xx...x..x.x."}},
    {9, "Tumbao", 16, {"...x..x....x..x.", "g..x..x.g..x..x.", "x..x..x.x..x..x."}},
    {9, "Montuno", 16, {"..x.x.x...x.x.x.", "..x.xAx...x.xAx.", "..x...x...x...x."}},
    {9, "Bossa Nova", 16, {"x..x..x...x..x..", "..x..x..x..x..x.", "A..x..x...A..x.."}},
    {9, "Samba", 16, {"x.xx..x.x.xx..x.", "A.xx..x.A.xx..x.", "x..x..x.x..x..x."}},
    {9, "Mambo", 16, {"x.xx.x.xx.x.xx.x", "A.xx.A.xx.x.xx.A", "x..x.x.x..x.x..x"}},
    {10, "Skank", 16, {"..x...x...x...x.", "..A...x...A...x.", "..x..gx...x..gx."}},
    {10, "Ska", 16, {"..x.x.x.x.x.x.x.", "..A...A...A...A.", "..x..gx..gx..gx."}},
    {10, "Nyabinghi", 16, {"x...x.x.x...x.x.", "A...x.x.A...x.x.", "x...x...x...x..."}},
    {10, "Dub", 16, {"..x-......x-....", "..A-......x.....", "..x...x-......x."}},
    {10, "Dembow", 16, {"x..x..x.x..x..x.", "A..x..x.A..x..x.", "x..xg.x.x..xg.x."}},
    {10, "Soca", 16, {"x.x.x.x.x.x.x.x.", "A.x.x.x.A.x.x.x.", "xxx.xxx.xxx.xxx."}},
    {10, "Calypso", 16, {"x..x.x.xx..x.x..", "A..x.x.xA..x.x..", "x..x.x..x..x.x.."}},
    {11, "Straight 8ths", 16, {"x.x.x.x.x.x.x.x.", "A.x.x.x.A.x.x.x.", "x...x...x...x..."}},
    {11, "Offbeat", 16, {"..x...x...x...x.", "..x.x.x...x.x.x.", "..A...x...A...x."}},
    {11, "Gallop", 16, {"x.xxx.xxx.xxx.xx", "x.x.x.x.x.x.x.x.", "xxx.xxx.xxx.xxx."}},
    {11, "Power Push", 16, {"x...x...x..x..x.", "x...x...x..x.x.x", "x...x...x...x..."}},
    {11, "Ballad", 16, {"x.......x.......", "x.......x-....x.", "x...x...x...x..."}},
    {11, "Anthem", 16, {"x...x...x.x.x...", "A...x...A.x.x...", "x...x...x...x..."}},
    {11, "Punk", 16, {"xxxxxxxxxxxxxxxx", "x.xxx.xxx.xxx.xx", "xxxxxxxx.xxxxxx."}},
    {11, "Folk Strum", 16, {"x---x-x-x-x-x-x-", "x---x-x-x-x-x-xx", "x---x---x-x-x---"}},
    {12, "Standard Bell", 12, {"x.x.xx.x.x.x", "x.xx.x.xx.x.", "A.x.xx.x.A.x"}},
    {12, "Highlife", 16, {"x.xxx.x.x.xxx.x.", "x.xx.xx.x.xx.xx.", "A.xxx.x.A.xxx.x."}},
    {12, "Afrobeat", 16, {"x.x.xxx.x.x.xxx.", "A.x.xxg.A.x.xxg.", "x.x.x.x.x.x.x.x."}},
    {12, "Soukous", 16, {"x.xxx.xxx.xxx.x.", "x.xx.xxx.xx.xxx.", "A.xxx.xxA.xxx.x."}},
    {12, "Makossa", 16, {"x.x.xx.xx.x.xx.x", "A.x.xxg.A.x.xxg.", "x.x.x.xx.x.x.xx."}},
    {12, "Mbaqanga", 16, {"x.xx.x.xx.xx.x.x", "x.xx.xx.x.xx.xx.", "A.xx.x.xA.xx.x.x"}},
    {13, "Maqsum", 16, {"A.x.x.A.x.x.x...", "A.x.xxA.x.x.xx..", "A.x.x.A.x.A...x."}},
    {13, "Baladi", 16, {"A.A.x.x.x.x.x...", "A.A.x.xxx.x.xx..", "A.A.x.x.A.x.x.x."}},
    {13, "Teental", 16, {"A.x.x.x.A.x.x.x.", "A.x.x.x.g.x.x.x.", "A.xxx.x.A.xxx.x."}},
    {13, "Buleria", 12, {"x.xx.xx.x.x.", "A.xA.xA.xx.x", "x.x.xx.x.x.x"}},
    {13, "Balkan 9", 18, {"A.x.A.x.A.x.A.x.x.", "A.x.x.A.x.x.A.x.x.", "A.x.A.x.x.A.x.A.x."}},
    {13, "Tango", 16, {"A...x.x.A...x.x.", "A.x.x.x.A...x.A.", "A...x.A.x...x.A."}},
};
#define GB_N 97
